language: python
sudo: false

env:
  - LUA="lua=5.2"
  - LUA="lua=5.3"

before_install:
  - pip install hererocks
  - hererocks lua_install -r^ --$LUA
  - export PATH=$PATH:$PWD/lua_install/bin
  
install:
  - luarocks install dkjson
  - luarocks install luasec
  - luarocks install luacheck

script:
  - luacheck -u *.lua
  - luarocks pack lvk-1.0-1.rockspec
#  - luarocks install lvk-1.0-1.src.rock
  - lua test-lvk.lua

notifications:
  email:
    on_success: never
    on_failure: always
